Algoritmo "nadador"
Var
n : inteiro
Inicio
escreva ("digite a idade do nadador ")
leia (n)
se (n > 17) entao
escreva ("nadador adulto")
senao
se (n > 13) e (n < 18) entao
escreva ("nadador juvenil b")
fimse
se (n > 10) e (n < 14) entao
escreva ("nadador juvenil a ")
fimse
se (n > 7) e (n < 11) entao
escreva ("nadador infantil b")
fimse
se (n > 4) e (n < 8) entao
escreva ("nadador infantil a")
fimse
fimse
Fimalgoritmo